GET http://localhost:3000/posts
Authorization: Bearer
yeJhgBciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5ODM5ODc1OX04cFcr70q-IkXlNpd7_cErd4U54rjjV_5-add9DIdl2E
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"yeJuYW1lIjoiS3lsZSIsImlhdCI6MTU5ODM05Dc1OX04cFcr70q-IkXlNpd7_cErd4U54rjjV_5-add9DIdl2EeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
}

###

POST http://localhost:4000/token
Content-Type: application/json
{
    "token": "08b48fecc313afe7cc4b910d681dd155dca43aaddae5c927a51f861cd068d36ccb3d7bb263e3c465012e792cf121f3d6c9147f81bd7362772fc9fea8ed176803"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}